// ===== PART 9: LOCALIZATION & ACCESSIBILITY =====
// Generated code for testing - Part 9 of 10

const Localization = {
  vi: {
    greeting: 'Xin chào',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    register: 'Đăng ký',
    booking: 'Đặt lịch',
    contact: 'Liên hệ',
    services: 'Dịch vụ',
    dashboard: 'Bảng điều khiển',
  },
  en: {
    greeting: 'Hello',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    booking: 'Booking',
    contact: 'Contact',
    services: 'Services',
    dashboard: 'Dashboard',
  },
};

const I18nHelper = {
  translate: (locale, key) => {
    const dictionary = Localization[locale] || Localization.vi;
    return dictionary[key] || key;
  },
  getLocaleFromPath: (path) => (path.startsWith('/en') ? 'en' : 'vi'),
};

const AccessibilityUtils = {
  announce: (message) => {
    const liveRegion = document.getElementById('a11y-live-region') || document.createElement('div');
    liveRegion.id = 'a11y-live-region';
    liveRegion.style.position = 'absolute';
    liveRegion.style.width = '1px';
    liveRegion.style.height = '1px';
    liveRegion.style.margin = '-1px';
    liveRegion.style.border = '0';
    liveRegion.style.padding = '0';
    liveRegion.style.overflow = 'hidden';
    liveRegion.style.clip = 'rect(0 0 0 0)';
    liveRegion.setAttribute('aria-live', 'assertive');
    liveRegion.textContent = message;
    document.body.appendChild(liveRegion);
  },

  isReadableColor: (foreground, background) => {
    const getLuminance = (color) => {
      const hex = color.replace('#', '');
      const rgb = [0, 2, 4].map((index) => parseInt(hex.substr(index, 2), 16) / 255).map((value) => {
        return value <= 0.03928 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
      });
      return 0.2126 * rgb[0] + 0.7152 * rgb[1] + 0.0722 * rgb[2];
    };
    const ratio = (Math.max(getLuminance(foreground), getLuminance(background)) + 0.05) /
      (Math.min(getLuminance(foreground), getLuminance(background)) + 0.05);
    return ratio >= 4.5;
  },
};

const A11yLabels = {
  closeButton: 'Đóng',
  openMenu: 'Mở menu',
  searchInput: 'Tìm kiếm',
  submitButton: 'Gửi',
};

const ErrorMessages = {
  required: 'Trường này là bắt buộc.',
  invalidEmail: 'Email không hợp lệ.',
  invalidPhone: 'Số điện thoại không hợp lệ.',
  minLength: (min) => `Phải có ít nhất ${min} ký tự.`,
  maxLength: (max) => `Không được vượt quá ${max} ký tự.`,
};

const AccessibilityTests = [
  { id: 'a1', item: 'Heading structure' },
  { id: 'a2', item: 'Color contrast' },
  { id: 'a3', item: 'Keyboard navigation' },
  { id: 'a4', item: 'ARIA attributes' },
];
const LocalizationSamples = [
  {
    id: 1,
    locale: 'en',
    key: 'sample.key.1',
    value: 'Sample text 1',
    description: 'Translation sample number 1 for locale en',
    category: 'generic',
  },
  {
    id: 2,
    locale: 'vi',
    key: 'sample.key.2',
    value: 'M?u van b?n 2',
    description: 'Translation sample number 2 for locale vi',
    category: 'generic',
  },
  {
    id: 3,
    locale: 'en',
    key: 'sample.key.3',
    value: 'Sample text 3',
    description: 'Translation sample number 3 for locale en',
    category: 'generic',
  },
  {
    id: 4,
    locale: 'vi',
    key: 'sample.key.4',
    value: 'M?u van b?n 4',
    description: 'Translation sample number 4 for locale vi',
    category: 'generic',
  },
  {
    id: 5,
    locale: 'en',
    key: 'sample.key.5',
    value: 'Sample text 5',
    description: 'Translation sample number 5 for locale en',
    category: 'generic',
  },
  {
    id: 6,
    locale: 'vi',
    key: 'sample.key.6',
    value: 'M?u van b?n 6',
    description: 'Translation sample number 6 for locale vi',
    category: 'generic',
  },
  {
    id: 7,
    locale: 'en',
    key: 'sample.key.7',
    value: 'Sample text 7',
    description: 'Translation sample number 7 for locale en',
    category: 'generic',
  },
  {
    id: 8,
    locale: 'vi',
    key: 'sample.key.8',
    value: 'M?u van b?n 8',
    description: 'Translation sample number 8 for locale vi',
    category: 'generic',
  },
  {
    id: 9,
    locale: 'en',
    key: 'sample.key.9',
    value: 'Sample text 9',
    description: 'Translation sample number 9 for locale en',
    category: 'generic',
  },
  {
    id: 10,
    locale: 'vi',
    key: 'sample.key.10',
    value: 'M?u van b?n 10',
    description: 'Translation sample number 10 for locale vi',
    category: 'generic',
  },
  {
    id: 11,
    locale: 'en',
    key: 'sample.key.11',
    value: 'Sample text 11',
    description: 'Translation sample number 11 for locale en',
    category: 'generic',
  },
  {
    id: 12,
    locale: 'vi',
    key: 'sample.key.12',
    value: 'M?u van b?n 12',
    description: 'Translation sample number 12 for locale vi',
    category: 'generic',
  },
  {
    id: 13,
    locale: 'en',
    key: 'sample.key.13',
    value: 'Sample text 13',
    description: 'Translation sample number 13 for locale en',
    category: 'generic',
  },
  {
    id: 14,
    locale: 'vi',
    key: 'sample.key.14',
    value: 'M?u van b?n 14',
    description: 'Translation sample number 14 for locale vi',
    category: 'generic',
  },
  {
    id: 15,
    locale: 'en',
    key: 'sample.key.15',
    value: 'Sample text 15',
    description: 'Translation sample number 15 for locale en',
    category: 'generic',
  },
  {
    id: 16,
    locale: 'vi',
    key: 'sample.key.16',
    value: 'M?u van b?n 16',
    description: 'Translation sample number 16 for locale vi',
    category: 'generic',
  },
  {
    id: 17,
    locale: 'en',
    key: 'sample.key.17',
    value: 'Sample text 17',
    description: 'Translation sample number 17 for locale en',
    category: 'generic',
  },
  {
    id: 18,
    locale: 'vi',
    key: 'sample.key.18',
    value: 'M?u van b?n 18',
    description: 'Translation sample number 18 for locale vi',
    category: 'generic',
  },
  {
    id: 19,
    locale: 'en',
    key: 'sample.key.19',
    value: 'Sample text 19',
    description: 'Translation sample number 19 for locale en',
    category: 'generic',
  },
  {
    id: 20,
    locale: 'vi',
    key: 'sample.key.20',
    value: 'M?u van b?n 20',
    description: 'Translation sample number 20 for locale vi',
    category: 'generic',
  },
  {
    id: 21,
    locale: 'en',
    key: 'sample.key.21',
    value: 'Sample text 21',
    description: 'Translation sample number 21 for locale en',
    category: 'generic',
  },
  {
    id: 22,
    locale: 'vi',
    key: 'sample.key.22',
    value: 'M?u van b?n 22',
    description: 'Translation sample number 22 for locale vi',
    category: 'generic',
  },
  {
    id: 23,
    locale: 'en',
    key: 'sample.key.23',
    value: 'Sample text 23',
    description: 'Translation sample number 23 for locale en',
    category: 'generic',
  },
  {
    id: 24,
    locale: 'vi',
    key: 'sample.key.24',
    value: 'M?u van b?n 24',
    description: 'Translation sample number 24 for locale vi',
    category: 'generic',
  },
  {
    id: 25,
    locale: 'en',
    key: 'sample.key.25',
    value: 'Sample text 25',
    description: 'Translation sample number 25 for locale en',
    category: 'generic',
  },
  {
    id: 26,
    locale: 'vi',
    key: 'sample.key.26',
    value: 'M?u van b?n 26',
    description: 'Translation sample number 26 for locale vi',
    category: 'generic',
  },
  {
    id: 27,
    locale: 'en',
    key: 'sample.key.27',
    value: 'Sample text 27',
    description: 'Translation sample number 27 for locale en',
    category: 'generic',
  },
  {
    id: 28,
    locale: 'vi',
    key: 'sample.key.28',
    value: 'M?u van b?n 28',
    description: 'Translation sample number 28 for locale vi',
    category: 'generic',
  },
  {
    id: 29,
    locale: 'en',
    key: 'sample.key.29',
    value: 'Sample text 29',
    description: 'Translation sample number 29 for locale en',
    category: 'generic',
  },
  {
    id: 30,
    locale: 'vi',
    key: 'sample.key.30',
    value: 'M?u van b?n 30',
    description: 'Translation sample number 30 for locale vi',
    category: 'generic',
  },
  {
    id: 31,
    locale: 'en',
    key: 'sample.key.31',
    value: 'Sample text 31',
    description: 'Translation sample number 31 for locale en',
    category: 'generic',
  },
  {
    id: 32,
    locale: 'vi',
    key: 'sample.key.32',
    value: 'M?u van b?n 32',
    description: 'Translation sample number 32 for locale vi',
    category: 'generic',
  },
  {
    id: 33,
    locale: 'en',
    key: 'sample.key.33',
    value: 'Sample text 33',
    description: 'Translation sample number 33 for locale en',
    category: 'generic',
  },
  {
    id: 34,
    locale: 'vi',
    key: 'sample.key.34',
    value: 'M?u van b?n 34',
    description: 'Translation sample number 34 for locale vi',
    category: 'generic',
  },
  {
    id: 35,
    locale: 'en',
    key: 'sample.key.35',
    value: 'Sample text 35',
    description: 'Translation sample number 35 for locale en',
    category: 'generic',
  },
  {
    id: 36,
    locale: 'vi',
    key: 'sample.key.36',
    value: 'M?u van b?n 36',
    description: 'Translation sample number 36 for locale vi',
    category: 'generic',
  },
  {
    id: 37,
    locale: 'en',
    key: 'sample.key.37',
    value: 'Sample text 37',
    description: 'Translation sample number 37 for locale en',
    category: 'generic',
  },
  {
    id: 38,
    locale: 'vi',
    key: 'sample.key.38',
    value: 'M?u van b?n 38',
    description: 'Translation sample number 38 for locale vi',
    category: 'generic',
  },
  {
    id: 39,
    locale: 'en',
    key: 'sample.key.39',
    value: 'Sample text 39',
    description: 'Translation sample number 39 for locale en',
    category: 'generic',
  },
  {
    id: 40,
    locale: 'vi',
    key: 'sample.key.40',
    value: 'M?u van b?n 40',
    description: 'Translation sample number 40 for locale vi',
    category: 'generic',
  },
  {
    id: 41,
    locale: 'en',
    key: 'sample.key.41',
    value: 'Sample text 41',
    description: 'Translation sample number 41 for locale en',
    category: 'generic',
  },
  {
    id: 42,
    locale: 'vi',
    key: 'sample.key.42',
    value: 'M?u van b?n 42',
    description: 'Translation sample number 42 for locale vi',
    category: 'generic',
  },
  {
    id: 43,
    locale: 'en',
    key: 'sample.key.43',
    value: 'Sample text 43',
    description: 'Translation sample number 43 for locale en',
    category: 'generic',
  },
  {
    id: 44,
    locale: 'vi',
    key: 'sample.key.44',
    value: 'M?u van b?n 44',
    description: 'Translation sample number 44 for locale vi',
    category: 'generic',
  },
  {
    id: 45,
    locale: 'en',
    key: 'sample.key.45',
    value: 'Sample text 45',
    description: 'Translation sample number 45 for locale en',
    category: 'generic',
  },
  {
    id: 46,
    locale: 'vi',
    key: 'sample.key.46',
    value: 'M?u van b?n 46',
    description: 'Translation sample number 46 for locale vi',
    category: 'generic',
  },
  {
    id: 47,
    locale: 'en',
    key: 'sample.key.47',
    value: 'Sample text 47',
    description: 'Translation sample number 47 for locale en',
    category: 'generic',
  },
  {
    id: 48,
    locale: 'vi',
    key: 'sample.key.48',
    value: 'M?u van b?n 48',
    description: 'Translation sample number 48 for locale vi',
    category: 'generic',
  },
  {
    id: 49,
    locale: 'en',
    key: 'sample.key.49',
    value: 'Sample text 49',
    description: 'Translation sample number 49 for locale en',
    category: 'generic',
  },
  {
    id: 50,
    locale: 'vi',
    key: 'sample.key.50',
    value: 'M?u van b?n 50',
    description: 'Translation sample number 50 for locale vi',
    category: 'generic',
  },
  {
    id: 51,
    locale: 'en',
    key: 'sample.key.51',
    value: 'Sample text 51',
    description: 'Translation sample number 51 for locale en',
    category: 'generic',
  },
  {
    id: 52,
    locale: 'vi',
    key: 'sample.key.52',
    value: 'M?u van b?n 52',
    description: 'Translation sample number 52 for locale vi',
    category: 'generic',
  },
  {
    id: 53,
    locale: 'en',
    key: 'sample.key.53',
    value: 'Sample text 53',
    description: 'Translation sample number 53 for locale en',
    category: 'generic',
  },
  {
    id: 54,
    locale: 'vi',
    key: 'sample.key.54',
    value: 'M?u van b?n 54',
    description: 'Translation sample number 54 for locale vi',
    category: 'generic',
  },
  {
    id: 55,
    locale: 'en',
    key: 'sample.key.55',
    value: 'Sample text 55',
    description: 'Translation sample number 55 for locale en',
    category: 'generic',
  },
  {
    id: 56,
    locale: 'vi',
    key: 'sample.key.56',
    value: 'M?u van b?n 56',
    description: 'Translation sample number 56 for locale vi',
    category: 'generic',
  },
  {
    id: 57,
    locale: 'en',
    key: 'sample.key.57',
    value: 'Sample text 57',
    description: 'Translation sample number 57 for locale en',
    category: 'generic',
  },
  {
    id: 58,
    locale: 'vi',
    key: 'sample.key.58',
    value: 'M?u van b?n 58',
    description: 'Translation sample number 58 for locale vi',
    category: 'generic',
  },
  {
    id: 59,
    locale: 'en',
    key: 'sample.key.59',
    value: 'Sample text 59',
    description: 'Translation sample number 59 for locale en',
    category: 'generic',
  },
  {
    id: 60,
    locale: 'vi',
    key: 'sample.key.60',
    value: 'M?u van b?n 60',
    description: 'Translation sample number 60 for locale vi',
    category: 'generic',
  },
  {
    id: 61,
    locale: 'en',
    key: 'sample.key.61',
    value: 'Sample text 61',
    description: 'Translation sample number 61 for locale en',
    category: 'generic',
  },
  {
    id: 62,
    locale: 'vi',
    key: 'sample.key.62',
    value: 'M?u van b?n 62',
    description: 'Translation sample number 62 for locale vi',
    category: 'generic',
  },
  {
    id: 63,
    locale: 'en',
    key: 'sample.key.63',
    value: 'Sample text 63',
    description: 'Translation sample number 63 for locale en',
    category: 'generic',
  },
  {
    id: 64,
    locale: 'vi',
    key: 'sample.key.64',
    value: 'M?u van b?n 64',
    description: 'Translation sample number 64 for locale vi',
    category: 'generic',
  },
  {
    id: 65,
    locale: 'en',
    key: 'sample.key.65',
    value: 'Sample text 65',
    description: 'Translation sample number 65 for locale en',
    category: 'generic',
  },
  {
    id: 66,
    locale: 'vi',
    key: 'sample.key.66',
    value: 'M?u van b?n 66',
    description: 'Translation sample number 66 for locale vi',
    category: 'generic',
  },
  {
    id: 67,
    locale: 'en',
    key: 'sample.key.67',
    value: 'Sample text 67',
    description: 'Translation sample number 67 for locale en',
    category: 'generic',
  },
  {
    id: 68,
    locale: 'vi',
    key: 'sample.key.68',
    value: 'M?u van b?n 68',
    description: 'Translation sample number 68 for locale vi',
    category: 'generic',
  },
  {
    id: 69,
    locale: 'en',
    key: 'sample.key.69',
    value: 'Sample text 69',
    description: 'Translation sample number 69 for locale en',
    category: 'generic',
  },
  {
    id: 70,
    locale: 'vi',
    key: 'sample.key.70',
    value: 'M?u van b?n 70',
    description: 'Translation sample number 70 for locale vi',
    category: 'generic',
  },
  {
    id: 71,
    locale: 'en',
    key: 'sample.key.71',
    value: 'Sample text 71',
    description: 'Translation sample number 71 for locale en',
    category: 'generic',
  },
  {
    id: 72,
    locale: 'vi',
    key: 'sample.key.72',
    value: 'M?u van b?n 72',
    description: 'Translation sample number 72 for locale vi',
    category: 'generic',
  },
  {
    id: 73,
    locale: 'en',
    key: 'sample.key.73',
    value: 'Sample text 73',
    description: 'Translation sample number 73 for locale en',
    category: 'generic',
  },
  {
    id: 74,
    locale: 'vi',
    key: 'sample.key.74',
    value: 'M?u van b?n 74',
    description: 'Translation sample number 74 for locale vi',
    category: 'generic',
  },
  {
    id: 75,
    locale: 'en',
    key: 'sample.key.75',
    value: 'Sample text 75',
    description: 'Translation sample number 75 for locale en',
    category: 'generic',
  },
  {
    id: 76,
    locale: 'vi',
    key: 'sample.key.76',
    value: 'M?u van b?n 76',
    description: 'Translation sample number 76 for locale vi',
    category: 'generic',
  },
  {
    id: 77,
    locale: 'en',
    key: 'sample.key.77',
    value: 'Sample text 77',
    description: 'Translation sample number 77 for locale en',
    category: 'generic',
  },
  {
    id: 78,
    locale: 'vi',
    key: 'sample.key.78',
    value: 'M?u van b?n 78',
    description: 'Translation sample number 78 for locale vi',
    category: 'generic',
  },
  {
    id: 79,
    locale: 'en',
    key: 'sample.key.79',
    value: 'Sample text 79',
    description: 'Translation sample number 79 for locale en',
    category: 'generic',
  },
  {
    id: 80,
    locale: 'vi',
    key: 'sample.key.80',
    value: 'M?u van b?n 80',
    description: 'Translation sample number 80 for locale vi',
    category: 'generic',
  },
  {
    id: 81,
    locale: 'en',
    key: 'sample.key.81',
    value: 'Sample text 81',
    description: 'Translation sample number 81 for locale en',
    category: 'generic',
  },
  {
    id: 82,
    locale: 'vi',
    key: 'sample.key.82',
    value: 'M?u van b?n 82',
    description: 'Translation sample number 82 for locale vi',
    category: 'generic',
  },
  {
    id: 83,
    locale: 'en',
    key: 'sample.key.83',
    value: 'Sample text 83',
    description: 'Translation sample number 83 for locale en',
    category: 'generic',
  },
  {
    id: 84,
    locale: 'vi',
    key: 'sample.key.84',
    value: 'M?u van b?n 84',
    description: 'Translation sample number 84 for locale vi',
    category: 'generic',
  },
  {
    id: 85,
    locale: 'en',
    key: 'sample.key.85',
    value: 'Sample text 85',
    description: 'Translation sample number 85 for locale en',
    category: 'generic',
  },
  {
    id: 86,
    locale: 'vi',
    key: 'sample.key.86',
    value: 'M?u van b?n 86',
    description: 'Translation sample number 86 for locale vi',
    category: 'generic',
  },
  {
    id: 87,
    locale: 'en',
    key: 'sample.key.87',
    value: 'Sample text 87',
    description: 'Translation sample number 87 for locale en',
    category: 'generic',
  },
  {
    id: 88,
    locale: 'vi',
    key: 'sample.key.88',
    value: 'M?u van b?n 88',
    description: 'Translation sample number 88 for locale vi',
    category: 'generic',
  },
  {
    id: 89,
    locale: 'en',
    key: 'sample.key.89',
    value: 'Sample text 89',
    description: 'Translation sample number 89 for locale en',
    category: 'generic',
  },
  {
    id: 90,
    locale: 'vi',
    key: 'sample.key.90',
    value: 'M?u van b?n 90',
    description: 'Translation sample number 90 for locale vi',
    category: 'generic',
  },
  {
    id: 91,
    locale: 'en',
    key: 'sample.key.91',
    value: 'Sample text 91',
    description: 'Translation sample number 91 for locale en',
    category: 'generic',
  },
  {
    id: 92,
    locale: 'vi',
    key: 'sample.key.92',
    value: 'M?u van b?n 92',
    description: 'Translation sample number 92 for locale vi',
    category: 'generic',
  },
  {
    id: 93,
    locale: 'en',
    key: 'sample.key.93',
    value: 'Sample text 93',
    description: 'Translation sample number 93 for locale en',
    category: 'generic',
  },
  {
    id: 94,
    locale: 'vi',
    key: 'sample.key.94',
    value: 'M?u van b?n 94',
    description: 'Translation sample number 94 for locale vi',
    category: 'generic',
  },
  {
    id: 95,
    locale: 'en',
    key: 'sample.key.95',
    value: 'Sample text 95',
    description: 'Translation sample number 95 for locale en',
    category: 'generic',
  },
  {
    id: 96,
    locale: 'vi',
    key: 'sample.key.96',
    value: 'M?u van b?n 96',
    description: 'Translation sample number 96 for locale vi',
    category: 'generic',
  },
  {
    id: 97,
    locale: 'en',
    key: 'sample.key.97',
    value: 'Sample text 97',
    description: 'Translation sample number 97 for locale en',
    category: 'generic',
  },
  {
    id: 98,
    locale: 'vi',
    key: 'sample.key.98',
    value: 'M?u van b?n 98',
    description: 'Translation sample number 98 for locale vi',
    category: 'generic',
  },
  {
    id: 99,
    locale: 'en',
    key: 'sample.key.99',
    value: 'Sample text 99',
    description: 'Translation sample number 99 for locale en',
    category: 'generic',
  },
  {
    id: 100,
    locale: 'vi',
    key: 'sample.key.100',
    value: 'M?u van b?n 100',
    description: 'Translation sample number 100 for locale vi',
    category: 'generic',
  },
  {
    id: 101,
    locale: 'en',
    key: 'sample.key.101',
    value: 'Sample text 101',
    description: 'Translation sample number 101 for locale en',
    category: 'generic',
  },
  {
    id: 102,
    locale: 'vi',
    key: 'sample.key.102',
    value: 'M?u van b?n 102',
    description: 'Translation sample number 102 for locale vi',
    category: 'generic',
  },
  {
    id: 103,
    locale: 'en',
    key: 'sample.key.103',
    value: 'Sample text 103',
    description: 'Translation sample number 103 for locale en',
    category: 'generic',
  },
  {
    id: 104,
    locale: 'vi',
    key: 'sample.key.104',
    value: 'M?u van b?n 104',
    description: 'Translation sample number 104 for locale vi',
    category: 'generic',
  },
  {
    id: 105,
    locale: 'en',
    key: 'sample.key.105',
    value: 'Sample text 105',
    description: 'Translation sample number 105 for locale en',
    category: 'generic',
  },
  {
    id: 106,
    locale: 'vi',
    key: 'sample.key.106',
    value: 'M?u van b?n 106',
    description: 'Translation sample number 106 for locale vi',
    category: 'generic',
  },
  {
    id: 107,
    locale: 'en',
    key: 'sample.key.107',
    value: 'Sample text 107',
    description: 'Translation sample number 107 for locale en',
    category: 'generic',
  },
  {
    id: 108,
    locale: 'vi',
    key: 'sample.key.108',
    value: 'M?u van b?n 108',
    description: 'Translation sample number 108 for locale vi',
    category: 'generic',
  },
  {
    id: 109,
    locale: 'en',
    key: 'sample.key.109',
    value: 'Sample text 109',
    description: 'Translation sample number 109 for locale en',
    category: 'generic',
  },
  {
    id: 110,
    locale: 'vi',
    key: 'sample.key.110',
    value: 'M?u van b?n 110',
    description: 'Translation sample number 110 for locale vi',
    category: 'generic',
  },
  {
    id: 111,
    locale: 'en',
    key: 'sample.key.111',
    value: 'Sample text 111',
    description: 'Translation sample number 111 for locale en',
    category: 'generic',
  },
  {
    id: 112,
    locale: 'vi',
    key: 'sample.key.112',
    value: 'M?u van b?n 112',
    description: 'Translation sample number 112 for locale vi',
    category: 'generic',
  },
  {
    id: 113,
    locale: 'en',
    key: 'sample.key.113',
    value: 'Sample text 113',
    description: 'Translation sample number 113 for locale en',
    category: 'generic',
  },
  {
    id: 114,
    locale: 'vi',
    key: 'sample.key.114',
    value: 'M?u van b?n 114',
    description: 'Translation sample number 114 for locale vi',
    category: 'generic',
  },
  {
    id: 115,
    locale: 'en',
    key: 'sample.key.115',
    value: 'Sample text 115',
    description: 'Translation sample number 115 for locale en',
    category: 'generic',
  },
  {
    id: 116,
    locale: 'vi',
    key: 'sample.key.116',
    value: 'M?u van b?n 116',
    description: 'Translation sample number 116 for locale vi',
    category: 'generic',
  },
  {
    id: 117,
    locale: 'en',
    key: 'sample.key.117',
    value: 'Sample text 117',
    description: 'Translation sample number 117 for locale en',
    category: 'generic',
  },
  {
    id: 118,
    locale: 'vi',
    key: 'sample.key.118',
    value: 'M?u van b?n 118',
    description: 'Translation sample number 118 for locale vi',
    category: 'generic',
  },
  {
    id: 119,
    locale: 'en',
    key: 'sample.key.119',
    value: 'Sample text 119',
    description: 'Translation sample number 119 for locale en',
    category: 'generic',
  },
  {
    id: 120,
    locale: 'vi',
    key: 'sample.key.120',
    value: 'M?u van b?n 120',
    description: 'Translation sample number 120 for locale vi',
    category: 'generic',
  },
];
