// ===== PART 7: ROUTING & STATE MANAGEMENT HELPERS =====
// Generated code for testing - Part 7 of 10

class EventEmitter {
  constructor() {
    this.events = {};
  }

  on(event, listener) {
    if (!this.events[event]) {
      this.events[event] = [];
    }
    this.events[event].push(listener);
  }

  off(event, listener) {
    if (!this.events[event]) return;
    this.events[event] = this.events[event].filter((l) => l !== listener);
  }

  emit(event, payload) {
    const listeners = this.events[event] || [];
    listeners.forEach((listener) => listener(payload));
  }
}

class HistoryManager {
  constructor() {
    this.stack = [];
    this.index = -1;
  }

  push(location) {
    this.stack = this.stack.slice(0, this.index + 1);
    this.stack.push(location);
    this.index++;
  }

  back() {
    if (this.index > 0) {
      this.index--;
      return this.stack[this.index];
    }
    return null;
  }

  forward() {
    if (this.index < this.stack.length - 1) {
      this.index++;
      return this.stack[this.index];
    }
    return null;
  }

  current() {
    return this.stack[this.index] || null;
  }
}

const RouteUtils = {
  matchPath: (pattern, path) => {
    const regex = new RegExp(`^${pattern.replace(/:[^/]+/g, '([^/]+)')}$`);
    const match = path.match(regex);
    if (!match) return null;
    const keys = (pattern.match(/:[^/]+/g) || []).map((param) => param.substring(1));
    return keys.reduce((result, key, index) => {
      result[key] = match[index + 1];
      return result;
    }, {});
  },
  parseQuery: (queryString) => {
    return queryString
      .replace(/^\?/, '')
      .split('&')
      .filter(Boolean)
      .reduce((params, segment) => {
        const [key, value] = segment.split('=');
        params[decodeURIComponent(key)] = decodeURIComponent(value || '');
        return params;
      }, {});
  },
};

class LocalStorageMock {
  constructor() {
    this.store = {};
  }

  getItem(key) {
    return this.store[key] || null;
  }

  setItem(key, value) {
    this.store[key] = value.toString();
  }

  removeItem(key) {
    delete this.store[key];
  }

  clear() {
    this.store = {};
  }
}

const PermissionLevels = {
  guest: 0,
  user: 1,
  staff: 2,
  admin: 3,
};

const AuthHelper = {
  canAccess: (role, requiredRole) => PermissionLevels[role] >= PermissionLevels[requiredRole],
  isAuthenticated: (token) => typeof token === 'string' && token.length > 0,
};

const NavigationMocks = {
  routes: [
    { path: '/', name: 'Home' },
    { path: '/services', name: 'Services' },
    { path: '/booking', name: 'Booking' },
    { path: '/admin', name: 'Admin' },
  ],
  buildMenu: function () {
    return this.routes.map((route) => ({
      key: route.path,
      label: route.name,
      path: route.path,
    }));
  },
};

const TestState = {
  user: {
    id: 101,
    name: 'Tran Thi B',
    role: 'user',
    status: 'active',
  },
  app: {
    currentPage: '/',
    locale: 'vi',
    theme: 'light',
  },
};
const ExtendedRouteMocks = [
  {
    id: 1,
    path: '/mock-route-1',
    name: 'Mock Route 1',
    component: 'MockComponent1',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-1',
  },
  {
    id: 2,
    path: '/mock-route-2',
    name: 'Mock Route 2',
    component: 'MockComponent2',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-2',
  },
  {
    id: 3,
    path: '/mock-route-3',
    name: 'Mock Route 3',
    component: 'MockComponent3',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-3',
  },
  {
    id: 4,
    path: '/mock-route-4',
    name: 'Mock Route 4',
    component: 'MockComponent4',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-4',
  },
  {
    id: 5,
    path: '/mock-route-5',
    name: 'Mock Route 5',
    component: 'MockComponent5',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-5',
  },
  {
    id: 6,
    path: '/mock-route-6',
    name: 'Mock Route 6',
    component: 'MockComponent6',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-6',
  },
  {
    id: 7,
    path: '/mock-route-7',
    name: 'Mock Route 7',
    component: 'MockComponent7',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-7',
  },
  {
    id: 8,
    path: '/mock-route-8',
    name: 'Mock Route 8',
    component: 'MockComponent8',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-8',
  },
  {
    id: 9,
    path: '/mock-route-9',
    name: 'Mock Route 9',
    component: 'MockComponent9',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-9',
  },
  {
    id: 10,
    path: '/mock-route-10',
    name: 'Mock Route 10',
    component: 'MockComponent10',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-10',
  },
  {
    id: 11,
    path: '/mock-route-11',
    name: 'Mock Route 11',
    component: 'MockComponent11',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-11',
  },
  {
    id: 12,
    path: '/mock-route-12',
    name: 'Mock Route 12',
    component: 'MockComponent12',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-12',
  },
  {
    id: 13,
    path: '/mock-route-13',
    name: 'Mock Route 13',
    component: 'MockComponent13',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-13',
  },
  {
    id: 14,
    path: '/mock-route-14',
    name: 'Mock Route 14',
    component: 'MockComponent14',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-14',
  },
  {
    id: 15,
    path: '/mock-route-15',
    name: 'Mock Route 15',
    component: 'MockComponent15',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-15',
  },
  {
    id: 16,
    path: '/mock-route-16',
    name: 'Mock Route 16',
    component: 'MockComponent16',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-16',
  },
  {
    id: 17,
    path: '/mock-route-17',
    name: 'Mock Route 17',
    component: 'MockComponent17',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-17',
  },
  {
    id: 18,
    path: '/mock-route-18',
    name: 'Mock Route 18',
    component: 'MockComponent18',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-18',
  },
  {
    id: 19,
    path: '/mock-route-19',
    name: 'Mock Route 19',
    component: 'MockComponent19',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-19',
  },
  {
    id: 20,
    path: '/mock-route-20',
    name: 'Mock Route 20',
    component: 'MockComponent20',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-20',
  },
  {
    id: 21,
    path: '/mock-route-21',
    name: 'Mock Route 21',
    component: 'MockComponent21',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-21',
  },
  {
    id: 22,
    path: '/mock-route-22',
    name: 'Mock Route 22',
    component: 'MockComponent22',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-22',
  },
  {
    id: 23,
    path: '/mock-route-23',
    name: 'Mock Route 23',
    component: 'MockComponent23',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-23',
  },
  {
    id: 24,
    path: '/mock-route-24',
    name: 'Mock Route 24',
    component: 'MockComponent24',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-24',
  },
  {
    id: 25,
    path: '/mock-route-25',
    name: 'Mock Route 25',
    component: 'MockComponent25',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-25',
  },
  {
    id: 26,
    path: '/mock-route-26',
    name: 'Mock Route 26',
    component: 'MockComponent26',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-26',
  },
  {
    id: 27,
    path: '/mock-route-27',
    name: 'Mock Route 27',
    component: 'MockComponent27',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-27',
  },
  {
    id: 28,
    path: '/mock-route-28',
    name: 'Mock Route 28',
    component: 'MockComponent28',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-28',
  },
  {
    id: 29,
    path: '/mock-route-29',
    name: 'Mock Route 29',
    component: 'MockComponent29',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-29',
  },
  {
    id: 30,
    path: '/mock-route-30',
    name: 'Mock Route 30',
    component: 'MockComponent30',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-30',
  },
  {
    id: 31,
    path: '/mock-route-31',
    name: 'Mock Route 31',
    component: 'MockComponent31',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-31',
  },
  {
    id: 32,
    path: '/mock-route-32',
    name: 'Mock Route 32',
    component: 'MockComponent32',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-32',
  },
  {
    id: 33,
    path: '/mock-route-33',
    name: 'Mock Route 33',
    component: 'MockComponent33',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-33',
  },
  {
    id: 34,
    path: '/mock-route-34',
    name: 'Mock Route 34',
    component: 'MockComponent34',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-34',
  },
  {
    id: 35,
    path: '/mock-route-35',
    name: 'Mock Route 35',
    component: 'MockComponent35',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-35',
  },
  {
    id: 36,
    path: '/mock-route-36',
    name: 'Mock Route 36',
    component: 'MockComponent36',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-36',
  },
  {
    id: 37,
    path: '/mock-route-37',
    name: 'Mock Route 37',
    component: 'MockComponent37',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-37',
  },
  {
    id: 38,
    path: '/mock-route-38',
    name: 'Mock Route 38',
    component: 'MockComponent38',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-38',
  },
  {
    id: 39,
    path: '/mock-route-39',
    name: 'Mock Route 39',
    component: 'MockComponent39',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-39',
  },
  {
    id: 40,
    path: '/mock-route-40',
    name: 'Mock Route 40',
    component: 'MockComponent40',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-40',
  },
  {
    id: 41,
    path: '/mock-route-41',
    name: 'Mock Route 41',
    component: 'MockComponent41',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-41',
  },
  {
    id: 42,
    path: '/mock-route-42',
    name: 'Mock Route 42',
    component: 'MockComponent42',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-42',
  },
  {
    id: 43,
    path: '/mock-route-43',
    name: 'Mock Route 43',
    component: 'MockComponent43',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-43',
  },
  {
    id: 44,
    path: '/mock-route-44',
    name: 'Mock Route 44',
    component: 'MockComponent44',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-44',
  },
  {
    id: 45,
    path: '/mock-route-45',
    name: 'Mock Route 45',
    component: 'MockComponent45',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-45',
  },
  {
    id: 46,
    path: '/mock-route-46',
    name: 'Mock Route 46',
    component: 'MockComponent46',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-46',
  },
  {
    id: 47,
    path: '/mock-route-47',
    name: 'Mock Route 47',
    component: 'MockComponent47',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-47',
  },
  {
    id: 48,
    path: '/mock-route-48',
    name: 'Mock Route 48',
    component: 'MockComponent48',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-48',
  },
  {
    id: 49,
    path: '/mock-route-49',
    name: 'Mock Route 49',
    component: 'MockComponent49',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-49',
  },
  {
    id: 50,
    path: '/mock-route-50',
    name: 'Mock Route 50',
    component: 'MockComponent50',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-50',
  },
  {
    id: 51,
    path: '/mock-route-51',
    name: 'Mock Route 51',
    component: 'MockComponent51',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-51',
  },
  {
    id: 52,
    path: '/mock-route-52',
    name: 'Mock Route 52',
    component: 'MockComponent52',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-52',
  },
  {
    id: 53,
    path: '/mock-route-53',
    name: 'Mock Route 53',
    component: 'MockComponent53',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-53',
  },
  {
    id: 54,
    path: '/mock-route-54',
    name: 'Mock Route 54',
    component: 'MockComponent54',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-54',
  },
  {
    id: 55,
    path: '/mock-route-55',
    name: 'Mock Route 55',
    component: 'MockComponent55',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-55',
  },
  {
    id: 56,
    path: '/mock-route-56',
    name: 'Mock Route 56',
    component: 'MockComponent56',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-56',
  },
  {
    id: 57,
    path: '/mock-route-57',
    name: 'Mock Route 57',
    component: 'MockComponent57',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-57',
  },
  {
    id: 58,
    path: '/mock-route-58',
    name: 'Mock Route 58',
    component: 'MockComponent58',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-58',
  },
  {
    id: 59,
    path: '/mock-route-59',
    name: 'Mock Route 59',
    component: 'MockComponent59',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-59',
  },
  {
    id: 60,
    path: '/mock-route-60',
    name: 'Mock Route 60',
    component: 'MockComponent60',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-60',
  },
  {
    id: 61,
    path: '/mock-route-61',
    name: 'Mock Route 61',
    component: 'MockComponent61',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-61',
  },
  {
    id: 62,
    path: '/mock-route-62',
    name: 'Mock Route 62',
    component: 'MockComponent62',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-62',
  },
  {
    id: 63,
    path: '/mock-route-63',
    name: 'Mock Route 63',
    component: 'MockComponent63',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-63',
  },
  {
    id: 64,
    path: '/mock-route-64',
    name: 'Mock Route 64',
    component: 'MockComponent64',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-64',
  },
  {
    id: 65,
    path: '/mock-route-65',
    name: 'Mock Route 65',
    component: 'MockComponent65',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-65',
  },
  {
    id: 66,
    path: '/mock-route-66',
    name: 'Mock Route 66',
    component: 'MockComponent66',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-66',
  },
  {
    id: 67,
    path: '/mock-route-67',
    name: 'Mock Route 67',
    component: 'MockComponent67',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-67',
  },
  {
    id: 68,
    path: '/mock-route-68',
    name: 'Mock Route 68',
    component: 'MockComponent68',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-68',
  },
  {
    id: 69,
    path: '/mock-route-69',
    name: 'Mock Route 69',
    component: 'MockComponent69',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-69',
  },
  {
    id: 70,
    path: '/mock-route-70',
    name: 'Mock Route 70',
    component: 'MockComponent70',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-70',
  },
  {
    id: 71,
    path: '/mock-route-71',
    name: 'Mock Route 71',
    component: 'MockComponent71',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-71',
  },
  {
    id: 72,
    path: '/mock-route-72',
    name: 'Mock Route 72',
    component: 'MockComponent72',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-72',
  },
  {
    id: 73,
    path: '/mock-route-73',
    name: 'Mock Route 73',
    component: 'MockComponent73',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-73',
  },
  {
    id: 74,
    path: '/mock-route-74',
    name: 'Mock Route 74',
    component: 'MockComponent74',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-74',
  },
  {
    id: 75,
    path: '/mock-route-75',
    name: 'Mock Route 75',
    component: 'MockComponent75',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-75',
  },
  {
    id: 76,
    path: '/mock-route-76',
    name: 'Mock Route 76',
    component: 'MockComponent76',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-76',
  },
  {
    id: 77,
    path: '/mock-route-77',
    name: 'Mock Route 77',
    component: 'MockComponent77',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-77',
  },
  {
    id: 78,
    path: '/mock-route-78',
    name: 'Mock Route 78',
    component: 'MockComponent78',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-78',
  },
  {
    id: 79,
    path: '/mock-route-79',
    name: 'Mock Route 79',
    component: 'MockComponent79',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-79',
  },
  {
    id: 80,
    path: '/mock-route-80',
    name: 'Mock Route 80',
    component: 'MockComponent80',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-80',
  },
  {
    id: 81,
    path: '/mock-route-81',
    name: 'Mock Route 81',
    component: 'MockComponent81',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-81',
  },
  {
    id: 82,
    path: '/mock-route-82',
    name: 'Mock Route 82',
    component: 'MockComponent82',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-82',
  },
  {
    id: 83,
    path: '/mock-route-83',
    name: 'Mock Route 83',
    component: 'MockComponent83',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-83',
  },
  {
    id: 84,
    path: '/mock-route-84',
    name: 'Mock Route 84',
    component: 'MockComponent84',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-84',
  },
  {
    id: 85,
    path: '/mock-route-85',
    name: 'Mock Route 85',
    component: 'MockComponent85',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-85',
  },
  {
    id: 86,
    path: '/mock-route-86',
    name: 'Mock Route 86',
    component: 'MockComponent86',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-86',
  },
  {
    id: 87,
    path: '/mock-route-87',
    name: 'Mock Route 87',
    component: 'MockComponent87',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-87',
  },
  {
    id: 88,
    path: '/mock-route-88',
    name: 'Mock Route 88',
    component: 'MockComponent88',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-88',
  },
  {
    id: 89,
    path: '/mock-route-89',
    name: 'Mock Route 89',
    component: 'MockComponent89',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-89',
  },
  {
    id: 90,
    path: '/mock-route-90',
    name: 'Mock Route 90',
    component: 'MockComponent90',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-90',
  },
  {
    id: 91,
    path: '/mock-route-91',
    name: 'Mock Route 91',
    component: 'MockComponent91',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-91',
  },
  {
    id: 92,
    path: '/mock-route-92',
    name: 'Mock Route 92',
    component: 'MockComponent92',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-92',
  },
  {
    id: 93,
    path: '/mock-route-93',
    name: 'Mock Route 93',
    component: 'MockComponent93',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-93',
  },
  {
    id: 94,
    path: '/mock-route-94',
    name: 'Mock Route 94',
    component: 'MockComponent94',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-94',
  },
  {
    id: 95,
    path: '/mock-route-95',
    name: 'Mock Route 95',
    component: 'MockComponent95',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-95',
  },
  {
    id: 96,
    path: '/mock-route-96',
    name: 'Mock Route 96',
    component: 'MockComponent96',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-96',
  },
  {
    id: 97,
    path: '/mock-route-97',
    name: 'Mock Route 97',
    component: 'MockComponent97',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-97',
  },
  {
    id: 98,
    path: '/mock-route-98',
    name: 'Mock Route 98',
    component: 'MockComponent98',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-98',
  },
  {
    id: 99,
    path: '/mock-route-99',
    name: 'Mock Route 99',
    component: 'MockComponent99',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-99',
  },
  {
    id: 100,
    path: '/mock-route-100',
    name: 'Mock Route 100',
    component: 'MockComponent100',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-100',
  },
  {
    id: 101,
    path: '/mock-route-101',
    name: 'Mock Route 101',
    component: 'MockComponent101',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-101',
  },
  {
    id: 102,
    path: '/mock-route-102',
    name: 'Mock Route 102',
    component: 'MockComponent102',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-102',
  },
  {
    id: 103,
    path: '/mock-route-103',
    name: 'Mock Route 103',
    component: 'MockComponent103',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-103',
  },
  {
    id: 104,
    path: '/mock-route-104',
    name: 'Mock Route 104',
    component: 'MockComponent104',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-104',
  },
  {
    id: 105,
    path: '/mock-route-105',
    name: 'Mock Route 105',
    component: 'MockComponent105',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-105',
  },
  {
    id: 106,
    path: '/mock-route-106',
    name: 'Mock Route 106',
    component: 'MockComponent106',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-106',
  },
  {
    id: 107,
    path: '/mock-route-107',
    name: 'Mock Route 107',
    component: 'MockComponent107',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-107',
  },
  {
    id: 108,
    path: '/mock-route-108',
    name: 'Mock Route 108',
    component: 'MockComponent108',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-108',
  },
  {
    id: 109,
    path: '/mock-route-109',
    name: 'Mock Route 109',
    component: 'MockComponent109',
    permission: 'user',
    group: 'Group B',
    exact: false,
    icon: 'icon-109',
  },
  {
    id: 110,
    path: '/mock-route-110',
    name: 'Mock Route 110',
    component: 'MockComponent110',
    permission: 'staff',
    group: 'Group C',
    exact: true,
    icon: 'icon-110',
  },
  {
    id: 111,
    path: '/mock-route-111',
    name: 'Mock Route 111',
    component: 'MockComponent111',
    permission: 'admin',
    group: 'Group D',
    exact: false,
    icon: 'icon-111',
  },
  {
    id: 112,
    path: '/mock-route-112',
    name: 'Mock Route 112',
    component: 'MockComponent112',
    permission: 'user',
    group: 'Group A',
    exact: true,
    icon: 'icon-112',
  },
  {
    id: 113,
    path: '/mock-route-113',
    name: 'Mock Route 113',
    component: 'MockComponent113',
    permission: 'staff',
    group: 'Group B',
    exact: false,
    icon: 'icon-113',
  },
  {
    id: 114,
    path: '/mock-route-114',
    name: 'Mock Route 114',
    component: 'MockComponent114',
    permission: 'admin',
    group: 'Group C',
    exact: true,
    icon: 'icon-114',
  },
  {
    id: 115,
    path: '/mock-route-115',
    name: 'Mock Route 115',
    component: 'MockComponent115',
    permission: 'user',
    group: 'Group D',
    exact: false,
    icon: 'icon-115',
  },
  {
    id: 116,
    path: '/mock-route-116',
    name: 'Mock Route 116',
    component: 'MockComponent116',
    permission: 'staff',
    group: 'Group A',
    exact: true,
    icon: 'icon-116',
  },
  {
    id: 117,
    path: '/mock-route-117',
    name: 'Mock Route 117',
    component: 'MockComponent117',
    permission: 'admin',
    group: 'Group B',
    exact: false,
    icon: 'icon-117',
  },
  {
    id: 118,
    path: '/mock-route-118',
    name: 'Mock Route 118',
    component: 'MockComponent118',
    permission: 'user',
    group: 'Group C',
    exact: true,
    icon: 'icon-118',
  },
  {
    id: 119,
    path: '/mock-route-119',
    name: 'Mock Route 119',
    component: 'MockComponent119',
    permission: 'staff',
    group: 'Group D',
    exact: false,
    icon: 'icon-119',
  },
  {
    id: 120,
    path: '/mock-route-120',
    name: 'Mock Route 120',
    component: 'MockComponent120',
    permission: 'admin',
    group: 'Group A',
    exact: true,
    icon: 'icon-120',
  },
];
